services:
  postiz-postgres:
    image: postgres:17-alpine
    container_name: postiz-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postiz-local-pwd
      POSTGRES_USER: postiz-local
      POSTGRES_DB: postiz-db-local
    volumes:
      - postiz-postgres-data:/var/lib/postgresql/data
    networks:
      - postiz-network
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postiz-local -d postiz-db-local"]
      interval: 10s
      timeout: 3s
      retries: 10

  postiz-redis:
    image: redis:7-alpine
    container_name: postiz-redis
    restart: unless-stopped
    volumes:
      - postiz-redis-data:/data
    networks:
      - postiz-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10

  postiz-prod:
    image: otomatisin/postiz:prod
    container_name: postiz-prod
    restart: unless-stopped
    depends_on:
      postiz-postgres:
        condition: service_healthy
      postiz-redis:
        condition: service_healthy
    networks:
      - postiz-network
    ports:
      - "127.0.0.1:5000:5000"
    env_file:
      - .env.prod
    volumes:
      - postiz-config:/app/config
      - postiz-uploads:/app/uploads
    environment:
      PORT: "3000"
      # DB
      DATABASE_URL: "postgresql://postiz-local:postiz-local-pwd@postiz-postgres:5432/postiz-db-local?schema=public"
      # Redis
      REDIS_URL: "redis://postiz-redis:6379"
      # Base URLs (sesuaikan dengan domain kamu)
      NEXT_PUBLIC_APP_URL: "https://app.otomatis.in"
      NEXT_PUBLIC_API_URL: "https://api.otomatis.in"

      APP_URL: "https://app.otomatis.in"
      PUBLIC_URL: "https://app.otomatis.in"
      BASE_URL: "https://app.otomatis.in"
      FRONTEND_URL: "https://app.otomatis.in"

volumes:
  postiz-postgres-data:
    name: postiz-postgres-data
  postiz-redis-data:
    name: postiz-redis-data
  postiz-config:
    name: postiz-config
  postiz-uploads:
    name: postiz-uploads

networks:
  postiz-network:
    external: true
